### ISSUE TITLE
Creating Bendpoints while creating a new Transition produces ClassCastException

### ISSUE THREAD

**Issue by StephanOpfer** [dasys-lab/alica-plan-designer-fx#104]
How to produce:

1. Choose the transition tool
2. Click on a state
3. Click an the empty canvas for a bendpoint

This is the Stacktrace I get:
`Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class javafx.scene.control.skin.ScrollPaneSkin$6 cannot be cast to class de.unikassel.vs.alica.planDesigner.view.editor.container.StateContainer (javafx.scene.control.skin.ScrollPaneSkin$6 and de.unikassel.vs.alica.planDesigner.view.editor.container.StateContainer are in unnamed module of loader 'app')
	at de.unikassel.vs.alica.planDesigner.view.editor.tools.transition.TransitionTool$2.handle(TransitionTool.java:107)
	at de.unikassel.vs.alica.planDesigner.view.editor.tools.transition.TransitionTool$2.handle(TransitionTool.java:95)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282)
	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3564)
	at javafx.scene.Scene$ClickGenerator.access$8200(Scene.java:3492)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3860)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by Schmidt1987** [comment]
Done :+1:
